[package]
name = "gui-gtk"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
description = "Ubuntu native frontend for Barrier"

[dependencies]
anyhow = "1.0"
async-channel = "2"
app-core = { path = "../app-core" }
tokio = { version = "1.35", features = ["rt-multi-thread"] }
gtk = { package = "gtk4", version = "0.8" }
adw = { package = "libadwaita", version = "0.6" }
env_logger = "0.10"
log = "0.4"
